name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_repositories: yes
          repositories_affiliations: owner, collaborator, organization_member
          repositories_skipped: ""
          committer_branch: main                    # 指定分支
          committer_message: "chore: update metrics [skip ci]"  # 正确参数名
